### ISSUE TITLE
Integrate Submodules

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#2]
- [x] Add gl-native: https://github.com/mapbox/mapbox-gl-native-ios/pull/12 - remember to modify the readme, and PR comment with the Git sha of the mapbox-gl-native submodule.
- [ ] ~Add Telemetry SDK~ Moved to #29 
- [x] Add Accounts SDK
- [x] ~Switch makefile to use "new" build system~ Create makefile at root of repo, that calls new build system.
- [x] Generate gl-native Xcode project (make iproj should now remain the same)
- [x] Build empty framework with gl-native ~& telemetry~ (telemetry include as currently)
- [ ] ~How to handle platform files in gl-native that include platform files in new repo 😢~ Moved to #51
- [ ] ~Related: How to split `darwin` files (and which ones)~ Moved to #51 
    - http_file_source.mm - we'll need some kind of delegate mechanism here
    - replace MGLLog macros with `mbgl::Log` equivalents.
- [ ] ~Ensure that mapbox-gl-native's makefile continues to function as expected for all platforms.~ Makefile is being removed.

**Comment by julianrex** [comment]
TODO: Create new tickets and close this one.

**Comment by fabian-guerra** [comment]
The remaining issues where ticketed in #29 and #51
